---
- hosts: all
  become: yes
  tasks:
    - name: Update all packages (Debian/Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_os_family == "Debian"
      notify: Reboot if needed

    - name: Update all packages (RedHat/CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
      notify: Reboot if needed

  handlers:
    - name: Reboot if needed
      reboot:
        msg: "Reboot initiated by Ansible after package upgrade."
        pre_reboot_delay: 60handlers:
  - name: Reboot if needed
    reboot:
      msg: "Reboot initiated by Ansible after package upgrade."
      pre_reboot_delay: 60
    when: inventory_hostname != "localhost"
